[package]
name = "neos-dj-controller-ws"
version = "0.1.1"
authors = ["danielle"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
midir = "0.7.0"
regex = "1.4.2"
websocket = "0.26.2"
